# Generated by Django 5.1.2 on 2024-10-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_club_city_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='district',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='postal_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
