# Generated by Django 5.1.2 on 2024-10-31 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_club_instagram_url_club_latitude_club_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='club_computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.clubscomputer', verbose_name='Компьютер'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата Окончания'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата Начала'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='computer_number',
            field=models.IntegerField(verbose_name='Номер Компьютера'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='cpu',
            field=models.CharField(max_length=100, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='gpu',
            field=models.CharField(max_length=100, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.instance', verbose_name='Инстанс'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='is_near_to_next',
            field=models.BooleanField(default=False, verbose_name='Рядом с Следующим'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='is_near_to_prev',
            field=models.BooleanField(default=False, verbose_name='Рядом с Предыдущим'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='ram',
            field=models.CharField(max_length=100, verbose_name='Оперативная Память'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='x_pos',
            field=models.IntegerField(verbose_name='Позиция по X'),
        ),
        migrations.AlterField(
            model_name='clubscomputer',
            name='y_pos',
            field=models.IntegerField(verbose_name='Позиция по Y'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='icon_url',
            field=models.URLField(verbose_name='URL на иконку'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userbonustransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='userbonustransaction',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='userbonustransaction',
            name='transaction_type',
            field=models.CharField(max_length=50, verbose_name='Тип Транзакции'),
        ),
        migrations.AlterField(
            model_name='userbonustransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='usermaintransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='usermaintransaction',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='usermaintransaction',
            name='transaction_type',
            field=models.CharField(max_length=50, verbose_name='Тип Транзакции'),
        ),
        migrations.AlterField(
            model_name='usermaintransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
