# Generated by Django 5.1.2 on 2024-10-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_appointment_club_computer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Номер Телефона'),
        ),
    ]
