# Generated by Django 5.1.2 on 2024-10-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_club_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='club',
            name='district',
            field=models.CharField(max_length=100, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='club',
            name='instagram_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='club',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='club',
            name='twogis_url',
            field=models.URLField(null=True, verbose_name='2gis'),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='club',
            name='whatsapp_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Whatsapp'),
        ),
    ]
