# Generated by Django 5.1.2 on 2024-11-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_club_description_alter_club_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
