# Generated by Django 5.1.2 on 2024-11-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_last_latitude_user_last_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='club',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='club',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Долгота'),
        ),
    ]
