# Generated by Django 5.1.2 on 2024-11-06 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_user_balance_alter_club_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='club_images/', verbose_name='Изображение')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.club', verbose_name='Клуб')),
            ],
        ),
    ]
